apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
type: Opaque
stringData:
  name: juicefsfors3
  metaurl: redis://127.0.0.1:6379/0
  storage: s3
  bucket: https://<bucketname>.s3.<region>.amazonaws.com
  access-key: <YourAccess>
  secret-key: <<YourSecret>>
