apiVersion: v1
kind: PersistentVolume
metadata:
  name: juicefs-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: juicefs-sc
  csi:
    driver: csi.juicefs.com
    volumeHandle: juicefs-pv-handle
    volumeAttributes:
    controllerPublishSecretRef:
      name: juicefs-secret
      namespace: default
    nodePublishSecretRef:
      name: juicefs-secret
      namespace: default
  claimRef:
    namespace: default
    name: juicefs-pvc

