apiVersion: kubeadm.k8s.io/v1beta4
caCertPath: /etc/kubernetes/pki/ca.crt
discovery:
  bootstrapToken:
    apiServerEndpoint: 172.30.196.172:6443
    caCertHashes:
    - sha256:abe4661a0d3d1a94ba2707b79cb9525b675e3e20f02b376dadfc07d7e6b038bb
    token: 65zhq9.86yy2dn21u1iui7z
  tlsBootstrapToken: 65zhq9.86yy2dn21u1iui7z
kind: JoinConfiguration
nodeRegistration:
  criSocket: unix:///var/run/cri-dockerd.sock
  imagePullPolicy: IfNotPresent
  imagePullSerial: true
  name: vivekyadav-vesu
  taints: null
timeouts:
  controlPlaneComponentHealthCheck: 4m0s
  discovery: 5m0s
  etcdAPICall: 2m0s
  kubeletHealthCheck: 4m0s
  kubernetesAPICall: 1m0s
  tlsBootstrap: 5m0s
  upgradeManifests: 5m0s
