apiVersion: kubeadm.k8s.io/v1beta3
kind: JoinConfiguration
discovery:
  bootstrapToken:
    apiServerEndpoint: "172.30.196.172:6443"
    token: "65zhq9.86yy2dn21u1iui7z"
    caCertHashes:
      - "sha256:abe4661a0d3d1a94ba2707b79cb9525b675e3e20f02b376dadfc07d7e6b038bb"
nodeRegistration:
  criSocket: "unix:///var/run/cri-dockerd.sock"