apiVersion: v1
kind: Secret
metadata:
  name: juicefs-secret
  namespace: default
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: pvc-c0f16509-30ba-46ef-8a46-94af3eed11bc
  metaurl: redis://:<password>@10.96.196.4:6379/1              
  access-key: <>
  secret-key: <>
  # token: cb924533a9caf90c7a76f5f89a7e74a337b88d72             