image:
  repository: juicedata/juicefs-csi-driver
  tag: "v0.25.2"
  pullPolicy: ""

globalConfig:
  enabled: true

serviceAccount:
  controller:
    create: true
    name: "juicefs-csi-controller-sa"
  node:
    create: true
    name: "juicefs-csi-node-sa"

controller:
  enabled: true
  provisioner: true

node:
  enabled: true

mountOptions:
  - debug  
