apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: locals3-juicefs-pvc
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Pi
  storageClassName: juicefs-sc
