apiVersion: v1
kind: Secret
metadata:
  name: locals3-juicefs-secret
  namespace: default
  labels:
    juicefs.com/validate-secret: "true"
type: Opaque
stringData:
  name: demo-juicefs-vol
  metaurl: "redis://:<password>@10.96.196.4:6379/1"
  storage: s3
  bucket: <>   
  access-key: <>
  secret-key: <> 
         
